name: Publish
on:
  push:
    branches:
      - main
concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  packages: write
  pull-requests: write
  repository-projects: write
  actions: write
  deployments: write

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v3
          with:
            cache: 'npm'
            node-version: 18
            registry-url: 'https://registry.npmjs.org'            
        - run: npm install --frozen-lockfile
        - name: Create release PR or publish
          id: release_step
          uses: changesets/action@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_SECRET }}
            NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}
          with:
            publish: npm run release
            createGithubReleases: true
    build:
      runs-on: ubuntu-latest
      needs: release
      steps:
        - run: echo Published ${{ needs.release.outputs.published }}
        - run: echo Packages ${{ needs.release.outputs.publishedPackages }}
    